-- Mortgage Underwriting Assistant: Infrastructure Bootstrap
-- Run as ACCOUNTADMIN

USE ROLE ACCOUNTADMIN;

-- 1. Create admin role
CREATE ROLE IF NOT EXISTS MORTGAGE_AGENT_ADMIN
  COMMENT = 'Admin role for Mortgage Underwriting Assistant demo - owns all objects';

GRANT ROLE MORTGAGE_AGENT_ADMIN TO ROLE ACCOUNTADMIN;
GRANT ROLE MORTGAGE_AGENT_ADMIN TO USER MKUKREJA;

-- 2. Create warehouse
CREATE WAREHOUSE IF NOT EXISTS MORTGAGE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  COMMENT = 'Warehouse for Mortgage Underwriting Assistant';

GRANT USAGE ON WAREHOUSE MORTGAGE_WH TO ROLE MORTGAGE_AGENT_ADMIN;
GRANT OPERATE ON WAREHOUSE MORTGAGE_WH TO ROLE MORTGAGE_AGENT_ADMIN;

-- 3. Create database and schema
CREATE DATABASE IF NOT EXISTS MORTGAGE_DEMO_DB
  COMMENT = 'Database for Mortgage Underwriting Assistant demo';

CREATE SCHEMA IF NOT EXISTS MORTGAGE_DEMO_DB.MORTGAGE_DEMO
  COMMENT = 'Schema for Mortgage Underwriting Assistant demo objects';

GRANT USAGE ON DATABASE MORTGAGE_DEMO_DB TO ROLE MORTGAGE_AGENT_ADMIN;
GRANT ALL ON SCHEMA MORTGAGE_DEMO_DB.MORTGAGE_DEMO TO ROLE MORTGAGE_AGENT_ADMIN;

-- 4. Grant schema-level CREATE privileges
GRANT CREATE TABLE ON SCHEMA MORTGAGE_DEMO_DB.MORTGAGE_DEMO TO ROLE MORTGAGE_AGENT_ADMIN;
GRANT CREATE STAGE ON SCHEMA MORTGAGE_DEMO_DB.MORTGAGE_DEMO TO ROLE MORTGAGE_AGENT_ADMIN;
GRANT CREATE PROCEDURE ON SCHEMA MORTGAGE_DEMO_DB.MORTGAGE_DEMO TO ROLE MORTGAGE_AGENT_ADMIN;
GRANT CREATE CORTEX SEARCH SERVICE ON SCHEMA MORTGAGE_DEMO_DB.MORTGAGE_DEMO TO ROLE MORTGAGE_AGENT_ADMIN;
GRANT CREATE SEMANTIC VIEW ON SCHEMA MORTGAGE_DEMO_DB.MORTGAGE_DEMO TO ROLE MORTGAGE_AGENT_ADMIN;

-- 5. Grant task execution privilege (required for scheduled tasks)
GRANT EXECUTE TASK ON ACCOUNT TO ROLE MORTGAGE_AGENT_ADMIN;

-- 6. Grant agent creation in SNOWFLAKE_INTELLIGENCE.AGENTS
GRANT USAGE ON DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE MORTGAGE_AGENT_ADMIN;
GRANT USAGE ON SCHEMA SNOWFLAKE_INTELLIGENCE.AGENTS TO ROLE MORTGAGE_AGENT_ADMIN;
GRANT CREATE AGENT ON SCHEMA SNOWFLAKE_INTELLIGENCE.AGENTS TO ROLE MORTGAGE_AGENT_ADMIN;
