-- Mortgage Underwriting Assistant: Table Definitions
-- Run as MORTGAGE_AGENT_ADMIN role

USE ROLE MORTGAGE_AGENT_ADMIN;
USE DATABASE MORTGAGE_DEMO_DB;
USE SCHEMA MORTGAGE_DEMO;
USE WAREHOUSE MORTGAGE_WH;

-- 1. Applicant Profiles
CREATE OR REPLACE TABLE APPLICANT_PROFILES (
    APPLICANT_ID        VARCHAR(20)   PRIMARY KEY,
    FULL_NAME           VARCHAR(100)  NOT NULL,
    ANNUAL_INCOME       NUMBER(12,2)  NOT NULL,
    CREDIT_SCORE        NUMBER(4,0)   NOT NULL,
    EMPLOYMENT_TYPE     VARCHAR(20)   NOT NULL,
    MONTHLY_DEBT_OBLIGATIONS NUMBER(10,2) NOT NULL
);

-- 2. Loan Applications
CREATE OR REPLACE TABLE LOAN_APPLICATIONS (
    APPLICATION_ID      VARCHAR(20)   PRIMARY KEY,
    APPLICANT_ID        VARCHAR(20)   NOT NULL REFERENCES APPLICANT_PROFILES(APPLICANT_ID),
    LOAN_AMOUNT         NUMBER(14,2)  NOT NULL,
    PROPERTY_VALUE      NUMBER(14,2)  NOT NULL,
    LOAN_PURPOSE        VARCHAR(20)   NOT NULL,
    STATUS              VARCHAR(20)   NOT NULL DEFAULT 'Pending'
);

-- 3. Exception Logs (audit trail for agent actions)
CREATE OR REPLACE TABLE EXCEPTION_LOGS (
    LOG_ID              VARCHAR(36)   PRIMARY KEY,
    APPLICATION_ID      VARCHAR(20)   NOT NULL,
    FLAG_REASON         VARCHAR(2000) NOT NULL,
    TIMESTAMP           TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);
