-- Mortgage Underwriting Assistant: PDF Ingestion and Cortex Search
-- Run as MORTGAGE_AGENT_ADMIN role

USE ROLE MORTGAGE_AGENT_ADMIN;
USE DATABASE MORTGAGE_DEMO_DB;
USE SCHEMA MORTGAGE_DEMO;
USE WAREHOUSE MORTGAGE_WH;

-- 1. Create stage for policy documents
CREATE STAGE IF NOT EXISTS MORTGAGE_DOCS_STAGE
  ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
  DIRECTORY = (ENABLE = TRUE);

-- 2. Upload PDFs (run from local machine)
-- PUT 'file:///path/to/pdfs/*.pdf' @MORTGAGE_DOCS_STAGE AUTO_COMPRESS=FALSE OVERWRITE=TRUE;

-- 3. Refresh stage directory
ALTER STAGE MORTGAGE_DOCS_STAGE REFRESH;

-- 4. Parse PDFs with AI and create documents table
CREATE OR REPLACE TABLE MORTGAGE_DOCUMENTS AS
SELECT
  RELATIVE_PATH AS DOC_FILENAME,
  AI_PARSE_DOCUMENT(
    TO_FILE('@MORTGAGE_DOCS_STAGE', RELATIVE_PATH),
    {'mode': 'LAYOUT'}
  ):content::VARCHAR AS DOC_CONTENT
FROM DIRECTORY(@MORTGAGE_DOCS_STAGE)
WHERE RELATIVE_PATH LIKE '%.pdf';

-- 5. Add metadata columns
ALTER TABLE MORTGAGE_DOCUMENTS ADD COLUMN DOC_TITLE VARCHAR, DOC_CATEGORY VARCHAR;

UPDATE MORTGAGE_DOCUMENTS SET DOC_TITLE = 'Credit Score Requirements Policy', DOC_CATEGORY = 'Credit Score Rules' WHERE DOC_FILENAME LIKE '%credit_score%';
UPDATE MORTGAGE_DOCUMENTS SET DOC_TITLE = 'Loan-to-Value Ratio Policy', DOC_CATEGORY = 'LTV Limits' WHERE DOC_FILENAME LIKE '%loan_to_value%';
UPDATE MORTGAGE_DOCUMENTS SET DOC_TITLE = 'Debt-to-Income Ratio Policy', DOC_CATEGORY = 'DTI Thresholds' WHERE DOC_FILENAME LIKE '%debt_to_income%';
UPDATE MORTGAGE_DOCUMENTS SET DOC_TITLE = 'Employment Type Requirements Policy', DOC_CATEGORY = 'Employment Type Requirements' WHERE DOC_FILENAME LIKE '%employment_type%';
UPDATE MORTGAGE_DOCUMENTS SET DOC_TITLE = 'Loan Purpose Restrictions Policy', DOC_CATEGORY = 'Loan Purpose Restrictions' WHERE DOC_FILENAME LIKE '%loan_purpose%';

-- 6. Enable change tracking (required for Cortex Search)
ALTER TABLE MORTGAGE_DOCUMENTS SET CHANGE_TRACKING = TRUE;

-- 7. Create Cortex Search service
CREATE OR REPLACE CORTEX SEARCH SERVICE MORTGAGE_POLICY_SEARCH
  ON DOC_CONTENT
  ATTRIBUTES DOC_TITLE, DOC_CATEGORY
  WAREHOUSE = MORTGAGE_WH
  TARGET_LAG = '1 hour'
AS (
  SELECT DOC_CONTENT, DOC_TITLE, DOC_CATEGORY
  FROM MORTGAGE_DOCUMENTS
);
