-- Mortgage Underwriting Assistant: Create User Role and Grants
-- Run as ACCOUNTADMIN

USE ROLE ACCOUNTADMIN;

-- 1. Create the user role
CREATE ROLE IF NOT EXISTS MORTGAGE_AGENT_USER
  COMMENT = 'User role for Mortgage Underwriting Assistant - read-only access to data, agent usage';

-- 2. Grant warehouse usage
GRANT USAGE ON WAREHOUSE MORTGAGE_WH TO ROLE MORTGAGE_AGENT_USER;

-- 3. Grant database and schema usage
GRANT USAGE ON DATABASE MORTGAGE_DEMO_DB TO ROLE MORTGAGE_AGENT_USER;
GRANT USAGE ON SCHEMA MORTGAGE_DEMO_DB.MORTGAGE_DEMO TO ROLE MORTGAGE_AGENT_USER;

-- 4. Grant SELECT on data tables
GRANT SELECT ON TABLE MORTGAGE_DEMO_DB.MORTGAGE_DEMO.APPLICANT_PROFILES TO ROLE MORTGAGE_AGENT_USER;
GRANT SELECT ON TABLE MORTGAGE_DEMO_DB.MORTGAGE_DEMO.LOAN_APPLICATIONS TO ROLE MORTGAGE_AGENT_USER;
GRANT SELECT ON TABLE MORTGAGE_DEMO_DB.MORTGAGE_DEMO.EXCEPTION_LOGS TO ROLE MORTGAGE_AGENT_USER;
GRANT SELECT ON TABLE MORTGAGE_DEMO_DB.MORTGAGE_DEMO.MORTGAGE_DOCUMENTS TO ROLE MORTGAGE_AGENT_USER;

-- 5. Grant usage on semantic view
GRANT SELECT ON SEMANTIC VIEW MORTGAGE_DEMO_DB.MORTGAGE_DEMO.MORTGAGE_SEMANTIC_VIEW TO ROLE MORTGAGE_AGENT_USER;

-- 6. Grant usage on Cortex Search service
GRANT USAGE ON CORTEX SEARCH SERVICE MORTGAGE_DEMO_DB.MORTGAGE_DEMO.MORTGAGE_POLICY_SEARCH TO ROLE MORTGAGE_AGENT_USER;

-- 7. Grant usage on agent
GRANT USAGE ON DATABASE SNOWFLAKE_INTELLIGENCE TO ROLE MORTGAGE_AGENT_USER;
GRANT USAGE ON SCHEMA SNOWFLAKE_INTELLIGENCE.AGENTS TO ROLE MORTGAGE_AGENT_USER;
GRANT USAGE ON AGENT SNOWFLAKE_INTELLIGENCE.AGENTS.MORTGAGE_UNDERWRITING_ASSISTANT TO ROLE MORTGAGE_AGENT_USER;

-- 8. Grant execute on stored procedure
GRANT USAGE ON PROCEDURE MORTGAGE_DEMO_DB.MORTGAGE_DEMO.FLAG_APPLICATION_EXCEPTION(VARCHAR, VARCHAR) TO ROLE MORTGAGE_AGENT_USER;

-- 9. Role hierarchy
GRANT ROLE MORTGAGE_AGENT_USER TO ROLE MORTGAGE_AGENT_ADMIN;

-- 10. Grant to specific users (modify as needed)
GRANT ROLE MORTGAGE_AGENT_USER TO USER MKUKREJA;
