-- Mortgage Underwriting Assistant: Teardown / Cleanup
-- Run as ACCOUNTADMIN
-- WARNING: This will permanently delete all demo objects!

USE ROLE ACCOUNTADMIN;

-- 1. Remove agent budget (must happen before agent drop)
ALTER AGENT IF EXISTS SNOWFLAKE_INTELLIGENCE.AGENTS.MORTGAGE_UNDERWRITING_ASSISTANT
  UNSET TAG MORTGAGE_DEMO_DB.MORTGAGE_DEMO.AGENT_COST_CENTER;
DROP SNOWFLAKE.CORE.BUDGET IF EXISTS MORTGAGE_DEMO_DB.MORTGAGE_DEMO.MORTGAGE_AGENT_BUDGET;
DROP PROCEDURE IF EXISTS MORTGAGE_DEMO_DB.MORTGAGE_DEMO.SP_REVOKE_AGENT_ACCESS();
DROP PROCEDURE IF EXISTS MORTGAGE_DEMO_DB.MORTGAGE_DEMO.SP_REINSTATE_AGENT_ACCESS();
DROP TAG IF EXISTS MORTGAGE_DEMO_DB.MORTGAGE_DEMO.AGENT_COST_CENTER;

-- 2. Drop the agent
DROP AGENT IF EXISTS SNOWFLAKE_INTELLIGENCE.AGENTS.MORTGAGE_UNDERWRITING_ASSISTANT;

-- 3. Drop Cortex Search service
DROP CORTEX SEARCH SERVICE IF EXISTS MORTGAGE_DEMO_DB.MORTGAGE_DEMO.MORTGAGE_POLICY_SEARCH;

-- 4. Drop semantic view
DROP SEMANTIC VIEW IF EXISTS MORTGAGE_DEMO_DB.MORTGAGE_DEMO.MORTGAGE_SEMANTIC_VIEW;

-- 5. Drop stored procedure
DROP PROCEDURE IF EXISTS MORTGAGE_DEMO_DB.MORTGAGE_DEMO.FLAG_APPLICATION_EXCEPTION(VARCHAR, VARCHAR);

-- 6. Remove data policies (must happen before table drops)
ALTER TABLE IF EXISTS MORTGAGE_DEMO_DB.MORTGAGE_DEMO.APPLICANT_PROFILES MODIFY COLUMN FULL_NAME UNSET MASKING POLICY;
ALTER TABLE IF EXISTS MORTGAGE_DEMO_DB.MORTGAGE_DEMO.APPLICANT_PROFILES MODIFY COLUMN ANNUAL_INCOME UNSET MASKING POLICY;
ALTER TABLE IF EXISTS MORTGAGE_DEMO_DB.MORTGAGE_DEMO.LOAN_APPLICATIONS DROP ROW ACCESS POLICY IF EXISTS MORTGAGE_DEMO_DB.MORTGAGE_DEMO.RAP_LOAN_APPLICATIONS;
DROP MASKING POLICY IF EXISTS MORTGAGE_DEMO_DB.MORTGAGE_DEMO.MASK_FULL_NAME;
DROP MASKING POLICY IF EXISTS MORTGAGE_DEMO_DB.MORTGAGE_DEMO.MASK_ANNUAL_INCOME;
DROP ROW ACCESS POLICY IF EXISTS MORTGAGE_DEMO_DB.MORTGAGE_DEMO.RAP_LOAN_APPLICATIONS;

-- 7. Drop tables
DROP TABLE IF EXISTS MORTGAGE_DEMO_DB.MORTGAGE_DEMO.EXCEPTION_LOGS;
DROP TABLE IF EXISTS MORTGAGE_DEMO_DB.MORTGAGE_DEMO.LOAN_APPLICATIONS;
DROP TABLE IF EXISTS MORTGAGE_DEMO_DB.MORTGAGE_DEMO.APPLICANT_PROFILES;
DROP TABLE IF EXISTS MORTGAGE_DEMO_DB.MORTGAGE_DEMO.MORTGAGE_DOCUMENTS;

-- 8. Drop stage
DROP STAGE IF EXISTS MORTGAGE_DEMO_DB.MORTGAGE_DEMO.MORTGAGE_DOCS_STAGE;

-- 9. Drop schema and database
DROP SCHEMA IF EXISTS MORTGAGE_DEMO_DB.MORTGAGE_DEMO;
DROP DATABASE IF EXISTS MORTGAGE_DEMO_DB;

-- 10. Drop warehouse
DROP WAREHOUSE IF EXISTS MORTGAGE_WH;

-- 11. Drop roles
DROP ROLE IF EXISTS MORTGAGE_AGENT_USER;
DROP ROLE IF EXISTS MORTGAGE_AGENT_ADMIN;
